NanoMichael/MicroTeX

src/platform/cairo/graphic_cairo.cpp
src/platform/cairo/graphic_cairo.h

See #10. Only tested this on Windows. I am not sure how this will interact with the `// already loaded` branch of `Font_cairo::loadFont` (probably not well), but I haven't been able to find any circumstance under which this branch is taken. For completeness, it would be good to do something to make sure `_fface` gets populated correctly in that case either way.

Store Cairo::FtFontFace with Font_cairo to fix Windows font loading.

---

src/res/parser/font_parser.cpp

Some `int`s have changed to `wchar_t` in one of the recent commits of font_parser; I've added explicit type conversions for these.
(Sorry, I think I did something wrong in the previous pull request, so I closed it - it's my first time creating a pull request! Hopefully this one works.)

Added type conversions

---

CMakeLists.txt
README.md
src/platform/cairo/graphic_cairo.cpp
src/platform/cairo/graphic_cairo.h
src/platform/gdi_win/graphic_win32.cpp
src/platform/qt/graphic_qt.cpp
src/platform/qt/graphic_qt.h
src/samples/gtkmm_main.cpp
src/samples/qt_main.cpp
src/samples/qt_mainwindow.cpp
src/samples/qt_mainwindow.h
src/samples/qt_texwidget.cpp
src/samples/qt_texwidget.h
src/samples/win32_main.cpp

Please find attached my initial Qt supporting version. For more details of problems see bug #26  . Also, this doesn't yet support the command line mode. The SVG button does nothing. The docs could be improved.
I've changed the build system to support Qt on more than one platform. I tried to do this cleanly. To build cmake needs a `-DQT=ON` option. I also reduced the cmake minimum version, as it seems to work ok on Ubuntu with this version (they're not shipping the currently required version).

Initial Qt supporting version

---

src/atom/atom_basic.cpp

Over at blackhole89/notekit#60, we were struggling with a crash due to a failed assertion under `atom_basic.cpp:483`. It turns out that trick used there to get the address from a shared_ptr does not work when _GLIBCXX_ASSERTIONS is defined and the pointer is NULL (as is the case with _previousAtom in that line at first). Indeed, if you check bits/shared_ptr_base.h, there's an assertion in the relevant operator* that the dereferenced pointer should not be NULL, regardless of the valid-ish use case of immediately taking its address again. I think the intended way of getting the underlying ptr is to use .get() instead.
I've only fixed the instance we bumped up against; if there are other places in the code with the `&(*smartptr)` pattern, they probably should changed in the same way too.

Get underlying ptr of shared_ptr without dereferencing.

---

meson.build
meson_options.txt
src/latex.cpp
src/latex.h

- I don't like that it throws a string if it doesn't find a resource location. I'd prefer to use somthing similar to Rust's `std::Result<std::String, Box<dyn std::error::Error>>` but I'm unable to figure out how enums work in c++. Please take a look at it.
- bumped version from 0.0.1 to 0.0.2
- meson can now build the demo aswell. (`meson _build -DTARGET_DEMO=true -DTARGET_LIB=false`).
Should close #38

initial support of resource detection &  meson demo target

---

CMakeLists.txt
meson.build
src/def.h.cmake.in
src/def.h.meson.in
src/latex.h

This MR adds:
- gcc that is lower than version nine is linked against `stdc++fs`
- gcc that is lower than version eight will use `experimental/filesystem` instead of `filesystem`
Please check the cmake files. I hate cmake - unsure if this works correctly

Legacy GCC Support

---

src/platform/qt/graphic_qt.cpp
src/platform/qt/graphic_qt.h
src/samples/gtkmm_main.cpp
src/samples/mem_check_main.cpp
src/samples/qt_main.cpp
src/samples/qt_mainwindow.h
src/samples/qt_texwidget.cpp
src/samples/qt_texwidget.h
src/samples/samples.h
src/samples/win32_main.cpp

Several errors occurs during compilation with MinGW for Qt. This patch fixes them.

fix compilation for Qt (namespaces)

---

.gitignore
CMakeLists.txt

Details:
1. separate library and executable files.
2. different platforms have different executable files.
3. rename all binary file to LaTeX.
Test Environment:
- for QT, Windows 10 Pro 20H2 Qt 6.0.0 msvc2019_64
- for UNIX(gtk), wsl ubuntu 20.04 gcc 9.3.0
Known issues:
- for WIN32, there are some bugs when build with MSVC.
I will fix them later.
- for SKIA, skia::skia target can't be imported normally.
The skia here is installed by `vcpkg.exe`.
```shell
vcpkg.exe install skia:x64-windows
```

rewrite CMakeLists.txt for better integration with other projects

---

.gitignore
CMakeLists.txt
example/CMakeLists.txt
example/latex2png.cpp

I write a simple demo to show how to use this library.
The example (latex2png) converts a latex snippet into a picture(.png) with Qt.
```
Usage: latex2png tex_name png_name
```

Add Example: latex2png

---

src/atom/atom_char.cpp
src/atom/atom_char.h
src/fonts/font_info.cpp
src/fonts/font_info.h

This a dirty PR to fix https://github.com/NanoMichael/cLaTeXMath/pull/73#issuecomment-842803855
I am very confused that all functions are implemented in the cpp file, but MSVC still reports errors.
```
error LNK2001: unresolved external symbol
```
When I move the code to the header(.h) file, the problem disappeared.
Maybe I can find better way to solve this bug later.

fix error LNK2001: unresolved external symbol

---

CMakeLists.txt
src/config.h
src/latex.h
src/platform/gdi_win/graphic_win32.h
src/platform/qt/graphic_qt.h
src/render.h

In win, we use `__declspec(dllexport)` to export symbols when building dll
and use `__declspec(dllimport)` to import symbols from dll.

fix: build dll in win32

---

example/gtk/meson.build
example/qt/qt_mainwindow.cpp
example/qt/qt_texqmlitem.cpp
example/qt/qt_texqmlitem.h
lib/meson.build
meson.build
meson_options.txt
platform/cairo/meson.build
platform/qt/graphic_qt.h
platform/qt/meson.build

I've noticed some issues with your latest changes to the buildfiles.
this should fix them :D
also btw, your changes introduced by 10a0e258c3433ab7d3d2fca6de7b0a694d89ddee have broken the otf2clm script, since it expects --batch or --single as first arg, but passes the first arg (in non-batch mode) as the otf filepath to batch_parse and instead it ignores the third passed param.

improved meson files & fixed qt-build and example

---

example/qt/meson.build
example/win32/meson.build
example/win32/win32_main.cpp
meson.build
meson_options.txt
platform/gdi_win/graphic_win32.cpp
platform/gdi_win/graphic_win32.h
platform/gdi_win/meson.build

now it is possible to build the gdi lib from meson too (but I've only tested with gcc & mingw, not microsoft's libs).
However gdi is not yet fully fixed yet. The new path methods of the Graphics2D class are not yet implemented, but I think one could implement it (https://docs.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-constructing-and-drawing-paths-use)
However at least on wine it still doesn't run, as it throws:
```
terminate called after throwing an instance of 'std::runtime_error'
what():  locale::facet::_S_create_c_locale name not valid
```
one can work around this, by replacing `locale("en_US.UTF-8")` with `locale("C")` in `lib/utils/utils.cpp`, but then the window only pops up for a frame, after which it throws:
```
terminate called after throwing an instance of …
```

meson GDI support + (missing qt exmaple)

---

platform/cairo/graphic_cairo.cpp
platform/cairo/graphic_cairo.h

this allows for duplicate inclusion of the header file

cairo: moved definitions of cairopp functions to source files

---

example/gtk/gtkmm_main.cpp
example/memcheck/mem_check_main.cpp
example/qt/qt_main.cpp
example/qtpng/latex2png.cpp
example/win32/win32_main.cpp
lib/CMakeLists.txt
lib/config.h
lib/otf/clm.cpp
lib/otf/fontsense.cpp
lib/otf/fontsense.h
lib/otf/meson.build
lib/otf/otf.h
lib/tinytex.cpp
lib/tinytex.h
lib/unimath/font_src.cpp
lib/unimath/font_src.h
platform/wasm/capi.cpp
prebuilt/otf2clm.py

In #87 you've said that
>> fallback fonts
>
> Probably no. In my submission, it is the user's responsibility to provide the font with the clm data file, but it needs to be discussed.
But for [NoteKit](https://github.com/blackhole89/notekit), we'd prefer if font handling will be done by clatexmath, rather than notekit. This PR is basically implementing a way of doing this:
It first looks at all potential tinytex data dirs (`$TINYTEX_FONTDIR`, `$XDG_DATA_HOME/tinytex`, `$XDG_DATA_DIRS[@]/tinytex`, `/usr/local/share/tinytex` and `/usr/share/tinytex`) and in for there to be a valid font there needs to be a `FontName.otf` and a `FontName.clm` file in these directories. 
The clm file spec has been changed to include postscript full name and postscript family name after the `has_glyph_path` byte …

WIP: Lookup fonts from filesystem

---

lib/microtex.cpp

This is to work arround the decimal parsing implementation that expects
comma as decimal seperator for de_DE (and maybe other langs to).
Currently $\LaTeX$ looks like this on a German system:

Set LC_NUMERIC to "C" on init

---

CMakeLists.txt
src/core/parser.cpp
src/fonts/font_basic.cpp
src/fonts/font_info.cpp
src/latex.cpp

1. Tweak CMakeLists.txt to use C++20.
2. Add std::to_string(fmt.chr) for wide character font output.
3. Add codecvt call to convert wstring to string where needed.
Closes https://github.com/NanoMichael/MicroTeX/issues/136

Add support for C++20.

---

platform/gtk/microtexequation.cpp

689ca83fc9926487fcda40f0d4104fd8c686724c broke some gir annotations, this should avoid this in the future

platform/gtk: fix GIR annotations that broke due to clang-format

---

lib/unimath/uni_symbol.cpp

MicroTeX should now render ![Bildschirmfoto vom 2023-06-16 08-54-13](https://github.com/NanoMichael/MicroTeX/assets/31540351/0d281430-82f5-4c5f-a8ba-d5279f43356a) when it receives \emptyset.
~~`\varnothing` currently also renders the same character (U+2205), it might be useful to make behave like TeX and cLaTeXMath and let it render ![Bildschirmfoto vom 2023-06-16 08-55-59](https://github.com/NanoMichael/MicroTeX/assets/31540351/7b20d417-7e43-4fc8-9b68-75144a0dfbc8), however I don't think unicode differentiates between them (maybe draw it in code? a circle and a line should be simple enough).~~
closes #138

unimath: added \emptyset symbol

---

.github/workflows/ubuntu.yml
lib/wrapper/meson.build
meson.build
platform/wasm/emscripten.cross
platform/wasm/meson.build
platform/wasm/prebuild-example-meson.sh
platform/wasm/prebuild-lib-meson.sh
platform/wasm/web/lib/context.js
platform/wasm/web/package-lock.json
platform/wasm/web/package.json

For some reason, when using the meson built microtex-wasm.wasm it initially starts to throw a few `microtex::ex_parse: Missing '['!` and `microtex::ex_parse: Missing '{'!` when switching rendering mode that don't occur with cmake. But since wasm seems impossible to debug, I didn't look into it further.
Also replaced a mirror that seems to be only resolvable in mainland china with the normal npmjs registry, as npm just hangs otherwise and it'll fail eventually (also using http instead of https 😬 ).

Added support for building wasm from meson

---

lib/CMakeLists.txt
lib/atom/atom.cpp
lib/atom/atom.h
lib/atom/atom_delim.h
lib/atom/atom_misc.cpp
lib/atom/atom_misc.h
lib/atom/atom_sideset.cpp
lib/atom/atom_sideset.h
lib/atom/atom_zstack.cpp
lib/atom/atom_zstack.h
lib/atom/meson.build
lib/core/formula.cpp
lib/macro/macro_accent.h
lib/macro/macro_fonts.cpp
lib/microtex.cpp
lib/microtex.h
lib/utils/exceptions.h
test/fuzzer/fuzz.sh

The following subset of minified crashlogs was used:
```
---
\begin{array}{{{}}}\resizebox0{
---
\sfrac$
---
\underbrace\newcolumntype
---
\begin{array}|\stackinset{}{}{}{
---
\accentset
---
\st\newcolumntype
---
\begin{split}\rotatebox{{{
---
\sideset$
---
```
There are a few crashes that contain `microtex::ArrayFormula::insertAtomIntoCol` in their Stacktrace, that end up crashing in libstdc++ `std::__shared_ptr<microtex::Atom, (__gnu_cxx::_Lock_policy)2>::__shared_ptr` function. I have yet to figure out what exactly causes this, as this appears to be in the end also a nullptr deref, however no nullptr is ever passed into `sptr`.
For example, `\begin{cases}&{}\\\\` causes this, any ideas?

Another large set of fuzzer fixes

---

lib/core/formula.cpp

I'm not quite use if I understood the functionality of `insertAtomIntoCol` correctly. Before merging please ensure that this didn't cause any regressions!
Crash reproducible using: `\begin{cases}&{}\\\\`

Fixed `insertAtomIntoCol` crash described in #163

---

lib/otf/clm.cpp

The size of the bool data type is implementation-defined. I'm on a platform where gcc defaults to bool being 4 bytes, not 1. Thus we should use u8 here instead of bool to make sure the code is portable.

Do not depend on bool being one byte

---

CMakeLists.txt
src/samples/qt_mainwindow.cpp
src/samples/qt_mainwindow.h
src/samples/qt_texwidget.cpp
src/samples/qt_texwidget.h

With little effort, Qt can write perfectly nice PDF files. Fonts are embedded automatically.
I think this is a neat alternative to SVG printing.
---
(there is also a class called QSvgGenerator, but it is less useful because it can not embed fonts, or convert text into paths).
---
(btw, I didn't manage Skia integration. Latest Skia code seems to have diverged too far).

Qt: Save as PDF
